"""Add is_from_gestion_real and ultimo_contacto_gr fields

Revision ID: eb1116c82879
Revises: 
Create Date: 2026-02-08 06:40:51.320807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb1116c82879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variables', mysql.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_key')
    )
    op.create_table('ticket_response_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('exceeded_threshold', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('auditorado', sa.Boolean(), nullable=True),
    sa.Column('assignment_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_response_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_response_metrics_ticket_id'), ['ticket_id'], unique=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_action'))
        batch_op.drop_index(batch_op.f('idx_entity'))
        batch_op.drop_index(batch_op.f('idx_performed_at'))

    with op.batch_alter_table('operator_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_person_id'))
        batch_op.drop_index(batch_op.f('person_id'))
        batch_op.create_index(batch_op.f('ix_operator_config_person_id'), ['person_id'], unique=True)

    with op.batch_alter_table('operator_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_day_of_week'))
        batch_op.drop_index(batch_op.f('idx_person_id'))
        batch_op.drop_index(batch_op.f('idx_schedule_type'))
        batch_op.create_index(batch_op.f('ix_operator_schedule_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_category'))
        batch_op.drop_index(batch_op.f('idx_key'))
        batch_op.drop_index(batch_op.f('key'))
        batch_op.create_index(batch_op.f('ix_system_config_key'), ['key'], unique=True)

    with op.batch_alter_table('ticket_reassignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_ticket_id'))
        batch_op.create_index(batch_op.f('ix_ticket_reassignment_history_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('tickets_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_from_gestion_real', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_contacto_gr', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='admin o operator',
               existing_nullable=False)
        batch_op.alter_column('person_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ID del operador asociado (si es operator)',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_person_id'))
        batch_op.drop_index(batch_op.f('idx_role'))
        batch_op.drop_index(batch_op.f('idx_username'))
        batch_op.drop_column('can_access_attention_dashboard')
        batch_op.drop_column('can_access_proactive_tickets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_access_proactive_tickets', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('can_access_attention_dashboard', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_person_id'), ['person_id'], unique=False)
        batch_op.alter_column('person_id',
               existing_type=mysql.INTEGER(),
               comment='ID del operador asociado (si es operator)',
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='admin o operator',
               existing_nullable=False)

    with op.batch_alter_table('tickets_detection', schema=None) as batch_op:
        batch_op.drop_column('ultimo_contacto_gr')
        batch_op.drop_column('is_from_gestion_real')

    with op.batch_alter_table('ticket_reassignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_reassignment_history_ticket_id'))
        batch_op.create_index(batch_op.f('idx_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_key'))
        batch_op.create_index(batch_op.f('key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('idx_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('idx_category'), ['category'], unique=False)

    with op.batch_alter_table('operator_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_schedule_person_id'))
        batch_op.create_index(batch_op.f('idx_schedule_type'), ['person_id', 'schedule_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_day_of_week'), ['day_of_week'], unique=False)

    with op.batch_alter_table('operator_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_config_person_id'))
        batch_op.create_index(batch_op.f('person_id'), ['person_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_performed_at'), ['performed_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_entity'), ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_action'), ['action'], unique=False)

    with op.batch_alter_table('ticket_response_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_response_metrics_ticket_id'))

    op.drop_table('ticket_response_metrics')
    op.drop_table('message_template')
    # ### end Alembic commands ###
